# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(318, 384)
        MainWindow.setMinimumSize(QtCore.QSize(318, 384))
        MainWindow.setMaximumSize(QtCore.QSize(318, 384))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_shapes = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_shapes.setGeometry(QtCore.QRect(130, 50, 131, 22))
        self.comboBox_shapes.setObjectName("comboBox_shapes")
        self.comboBox_shapes.addItem("")
        self.comboBox_shapes.setItemText(0, "")
        self.comboBox_shapes.addItem("")
        self.comboBox_shapes.addItem("")
        self.comboBox_shapes.addItem("")
        self.comboBox_shapes.addItem("")
        self.comboBox_shapes.addItem("")
        self.lineEdit_dimension_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dimension_1.setEnabled(False)
        self.lineEdit_dimension_1.setGeometry(QtCore.QRect(130, 100, 131, 20))
        self.lineEdit_dimension_1.setObjectName("lineEdit_dimension_1")
        self.lineEdit_dimension_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dimension_2.setEnabled(False)
        self.lineEdit_dimension_2.setGeometry(QtCore.QRect(130, 130, 131, 20))
        self.lineEdit_dimension_2.setObjectName("lineEdit_dimension_2")
        self.pushButton_area = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_area.setGeometry(QtCore.QRect(130, 190, 61, 21))
        self.pushButton_area.setObjectName("pushButton_area")
        self.pushButton_perim = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_perim.setGeometry(QtCore.QRect(200, 190, 61, 21))
        self.pushButton_perim.setObjectName("pushButton_perim")
        self.label_shape = QtWidgets.QLabel(self.centralwidget)
        self.label_shape.setGeometry(QtCore.QRect(90, 50, 31, 21))
        self.label_shape.setObjectName("label_shape")
        self.label_dimension_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_dimension_1.setGeometry(QtCore.QRect(30, 100, 91, 21))
        self.label_dimension_1.setText("")
        self.label_dimension_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dimension_1.setObjectName("label_dimension_1")
        self.label_dimension_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_dimension_2.setGeometry(QtCore.QRect(30, 130, 91, 21))
        self.label_dimension_2.setText("")
        self.label_dimension_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dimension_2.setObjectName("label_dimension_2")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(50, 230, 211, 91))
        self.label_output.setText("")
        self.label_output.setObjectName("label_output")
        self.lineEdit_dimension_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dimension_3.setEnabled(False)
        self.lineEdit_dimension_3.setGeometry(QtCore.QRect(130, 160, 131, 20))
        self.lineEdit_dimension_3.setObjectName("lineEdit_dimension_3")
        self.label_dimension_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_dimension_3.setGeometry(QtCore.QRect(30, 160, 91, 21))
        self.label_dimension_3.setText("")
        self.label_dimension_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dimension_3.setObjectName("label_dimension_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 318, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shape Calculator"))
        self.comboBox_shapes.setItemText(1, _translate("MainWindow", "Square"))
        self.comboBox_shapes.setItemText(2, _translate("MainWindow", "Rectangle"))
        self.comboBox_shapes.setItemText(3, _translate("MainWindow", "Circle"))
        self.comboBox_shapes.setItemText(4, _translate("MainWindow", "Triangle"))
        self.comboBox_shapes.setItemText(5, _translate("MainWindow", "Triangle (h/w)"))
        self.pushButton_area.setText(_translate("MainWindow", "Area"))
        self.pushButton_perim.setText(_translate("MainWindow", "Perimeter"))
        self.label_shape.setText(_translate("MainWindow", "Shape"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
